[package]
name = "dice"
version = "0.1.0"
authors = ["Joshua Lockerman"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pest = "2"
pest_derive = "2"
once_cell = "1"
rand = "0.7.3"
rustyline = "6"
